// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string):Promise<void>;

export function CreateAccount(arg1:string,arg2:string,arg3:string):Promise<main.AccountView>;

export function DeleteMessage(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function DropFiles(arg1:Array<string>):Promise<void>;

export function EditMessage(arg1:string,arg2:string):Promise<void>;

export function ExportAccount(arg1:string):Promise<string>;

export function FetchLinkPreview(arg1:string):Promise<main.LinkPreview>;

export function GetAccountInfo():Promise<main.AccountView>;

export function GetBoards(arg1:string):Promise<Array<main.Board>>;

export function GetFileURL(arg1:string):Promise<string>;

export function GetFingerprint():Promise<string>;

export function GetMessagesAround(arg1:string,arg2:string):Promise<Array<main.ChatMessage>>;

export function GetMessagesBefore(arg1:string,arg2:string):Promise<Array<main.ChatMessage>>;

export function GetProfilePicture():Promise<string>;

export function GetRooms():Promise<Array<main.Room>>;

export function GetServerInfo(arg1:string):Promise<main.ServerInfo>;

export function GetServers():Promise<Array<main.SavedServer>>;

export function GetUsername():Promise<string>;

export function HasAccount():Promise<boolean>;

export function ImportAccount(arg1:string,arg2:string):Promise<main.AccountView>;

export function IsDeafened():Promise<boolean>;

export function IsMuted():Promise<boolean>;

export function JoinVoiceChannel(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function LeaveVoiceChannel():Promise<void>;

export function ListAccounts():Promise<Array<main.AccountSummary>>;

export function PickAccountFile():Promise<string>;

export function PickAccountFolder():Promise<string>;

export function PickFiles():Promise<Array<string>>;

export function PickPfp():Promise<string>;

export function PingServer():Promise<number>;

export function ReadImageAsDataURL(arg1:string):Promise<string>;

export function RemoveServer(arg1:string):Promise<Array<main.SavedServer>>;

export function SaveProfilePicture(arg1:string):Promise<void>;

export function SearchServer(arg1:string):Promise<Array<main.SearchResult>>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<main.Attachment>):Promise<void>;

export function StartMicTest(arg1:string,arg2:string):Promise<void>;

export function StopMicTest():Promise<void>;

export function SubscribeBoard(arg1:string):Promise<void>;

export function ToggleDeafen():Promise<boolean>;

export function ToggleMute():Promise<boolean>;

export function UnlockAccount(arg1:string):Promise<main.AccountView>;

export function UploadFile(arg1:string):Promise<main.UploadResult>;
