// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DropFiles(arg1) {
  return window['go']['main']['App']['DropFiles'](arg1);
}

export function EditMessage(arg1, arg2) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2);
}

export function FetchLinkPreview(arg1) {
  return window['go']['main']['App']['FetchLinkPreview'](arg1);
}

export function GetBoards(arg1) {
  return window['go']['main']['App']['GetBoards'](arg1);
}

export function GetFileURL(arg1) {
  return window['go']['main']['App']['GetFileURL'](arg1);
}

export function GetRooms() {
  return window['go']['main']['App']['GetRooms']();
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SubscribeBoard(arg1) {
  return window['go']['main']['App']['SubscribeBoard'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}
