// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function CreateAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DropFiles(arg1) {
  return window['go']['main']['App']['DropFiles'](arg1);
}

export function EditMessage(arg1, arg2) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2);
}

export function ExportAccount(arg1, arg2) {
  return window['go']['main']['App']['ExportAccount'](arg1, arg2);
}

export function FetchLinkPreview(arg1) {
  return window['go']['main']['App']['FetchLinkPreview'](arg1);
}

export function GetAccountInfo() {
  return window['go']['main']['App']['GetAccountInfo']();
}

export function GetBoards(arg1) {
  return window['go']['main']['App']['GetBoards'](arg1);
}

export function GetFileURL(arg1) {
  return window['go']['main']['App']['GetFileURL'](arg1);
}

export function GetFingerprint() {
  return window['go']['main']['App']['GetFingerprint']();
}

export function GetMessagesAround(arg1, arg2) {
  return window['go']['main']['App']['GetMessagesAround'](arg1, arg2);
}

export function GetMessagesBefore(arg1, arg2) {
  return window['go']['main']['App']['GetMessagesBefore'](arg1, arg2);
}

export function GetRooms() {
  return window['go']['main']['App']['GetRooms']();
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function HasAccount() {
  return window['go']['main']['App']['HasAccount']();
}

export function ImportAccount(arg1, arg2) {
  return window['go']['main']['App']['ImportAccount'](arg1, arg2);
}

export function JoinVoiceChannel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['JoinVoiceChannel'](arg1, arg2, arg3, arg4);
}

export function LeaveVoiceChannel() {
  return window['go']['main']['App']['LeaveVoiceChannel']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function PickAccountFile() {
  return window['go']['main']['App']['PickAccountFile']();
}

export function PickAccountFolder() {
  return window['go']['main']['App']['PickAccountFolder']();
}

export function PickExportDestination() {
  return window['go']['main']['App']['PickExportDestination']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickPfp() {
  return window['go']['main']['App']['PickPfp']();
}

export function PingServer() {
  return window['go']['main']['App']['PingServer']();
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function SearchServer(arg1) {
  return window['go']['main']['App']['SearchServer'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function StartMicTest(arg1, arg2) {
  return window['go']['main']['App']['StartMicTest'](arg1, arg2);
}

export function StopMicTest() {
  return window['go']['main']['App']['StopMicTest']();
}

export function SubscribeBoard(arg1) {
  return window['go']['main']['App']['SubscribeBoard'](arg1);
}

export function UnlockAccount(arg1) {
  return window['go']['main']['App']['UnlockAccount'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}
