// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DropFiles(arg1:Array<string>):Promise<void>;

export function EditMessage(arg1:string,arg2:string):Promise<void>;

export function FetchLinkPreview(arg1:string):Promise<main.LinkPreview>;

export function GetBoards(arg1:string):Promise<Array<main.Board>>;

export function GetFileURL(arg1:string):Promise<string>;

export function GetRooms():Promise<Array<main.Room>>;

export function GetServerInfo(arg1:string):Promise<main.ServerInfo>;

export function GetServers():Promise<Array<main.SavedServer>>;

export function GetUsername():Promise<string>;

export function PickFiles():Promise<Array<string>>;

export function RemoveServer(arg1:string):Promise<Array<main.SavedServer>>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<main.Attachment>):Promise<void>;

export function SubscribeBoard(arg1:string):Promise<void>;

export function UploadFile(arg1:string):Promise<main.UploadResult>;
