// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AccountAvatar(arg1:string):Promise<string>;

export function ActiveAccount():Promise<main.AccountSummary>;

export function CameraModes(arg1:string):Promise<Array<main.CameraMode>>;

export function CancelAccountExport():Promise<void>;

export function CancelConversion(arg1:string):Promise<void>;

export function CaptureEncoders():Promise<Array<main.EncoderChoice>>;

export function Connect(arg1:string,arg2:string):Promise<void>;

export function ConvertVideoForPlayback(arg1:string,arg2:string):Promise<string>;

export function CreateAccount(arg1:string,arg2:string,arg3:string):Promise<main.AccountView>;

export function CreateInvite():Promise<main.InviteInfo>;

export function DeleteEmoji(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteSticker(arg1:string):Promise<void>;

export function DiscardConverted(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DropFiles(arg1:Array<string>):Promise<void>;

export function EditMessage(arg1:string,arg2:string):Promise<void>;

export function ExportAccount(arg1:string):Promise<string>;

export function FetchLinkPreview(arg1:string):Promise<main.LinkPreview>;

export function FetchRoles():Promise<string>;

export function FetchServerBanner():Promise<string>;

export function FetchServerIcon(arg1:string):Promise<string>;

export function FetchServerThemeBackground():Promise<string>;

export function FetchUserPfp(arg1:string):Promise<string>;

export function FetchUserProfile(arg1:string):Promise<main.UserProfile>;

export function GetAccountInfo():Promise<main.AccountView>;

export function GetBoards(arg1:string):Promise<Array<main.Board>>;

export function GetClientSettings():Promise<string>;

export function GetConnectionSecurity():Promise<main.ConnectionSecurity>;

export function GetEmojis():Promise<Array<main.CustomEmoji>>;

export function GetFileLink(arg1:string):Promise<string>;

export function GetFileURL(arg1:string):Promise<string>;

export function GetFingerprint():Promise<string>;

export function GetMessagesAround(arg1:string,arg2:string):Promise<Array<main.ChatMessage>>;

export function GetMessagesBefore(arg1:string,arg2:string):Promise<Array<main.ChatMessage>>;

export function GetOwnProfile():Promise<main.OwnProfile>;

export function GetPinnedMessages(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetProfilePicture():Promise<string>;

export function GetRooms():Promise<Array<main.Room>>;

export function GetServerInfo(arg1:string):Promise<main.ServerInfo>;

export function GetServers():Promise<Array<main.SavedServer>>;

export function GetStickers():Promise<Array<main.Sticker>>;

export function GetSystemIdleSeconds():Promise<number>;

export function GetUsername():Promise<string>;

export function HasAccount():Promise<boolean>;

export function ImageFromURL(arg1:string):Promise<main.EmojiFile>;

export function ImportAccount(arg1:string,arg2:string):Promise<main.AccountView>;

export function InVoiceCall():Promise<boolean>;

export function IsDeafened():Promise<boolean>;

export function IsMuted():Promise<boolean>;

export function JoinVoiceChannel(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function JoinWithInvite(arg1:string,arg2:string):Promise<void>;

export function KickMember(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function LeaveVoiceChannel():Promise<void>;

export function ListAccounts():Promise<Array<main.AccountSummary>>;

export function ListCameras():Promise<Array<main.CameraDevice>>;

export function ListShareSources():Promise<Array<main.ShareSource>>;

export function LogOut():Promise<void>;

export function MoveBoard(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveRooms(arg1:Array<string>):Promise<void>;

export function NativeCaptureInfo():Promise<Record<string, any>>;

export function OpenAttachmentExternally(arg1:string,arg2:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickAccountFile():Promise<string>;

export function PickAccountFolder():Promise<string>;

export function PickBackgroundImage():Promise<string>;

export function PickBanner():Promise<string>;

export function PickFiles():Promise<Array<string>>;

export function PickImageFiles(arg1:string):Promise<Array<string>>;

export function PickPfp():Promise<string>;

export function PingServer():Promise<number>;

export function PrepareAccountExport(arg1:string,arg2:string):Promise<string>;

export function PushVideoFrame(arg1:string,arg2:number):Promise<void>;

export function ReactToMessage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ReadImageAsDataURL(arg1:string):Promise<string>;

export function ReadImageFiles(arg1:Array<string>):Promise<Array<main.EmojiFile>>;

export function RecheckGPUEncoder():Promise<Record<string, any>>;

export function ReconnectVoice(arg1:Array<string>):Promise<void>;

export function RemoveServer(arg1:string):Promise<Array<main.SavedServer>>;

export function ReorderServers(arg1:Array<string>):Promise<Array<main.SavedServer>>;

export function RequestScreenKeyframe(arg1:string):Promise<void>;

export function RequestVideoKeyframe(arg1:string):Promise<void>;

export function ResolveServerAddress(arg1:string):Promise<string>;

export function RestartToUpdate():Promise<void>;

export function SaveAccountExport():Promise<string>;

export function SaveClientSettings(arg1:string):Promise<void>;

export function SaveProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveProfilePicture(arg1:string):Promise<void>;

export function ScreenShareInfo():Promise<Record<string, any>>;

export function SearchServer(arg1:string):Promise<Array<main.SearchResult>>;

export function SearchServerFiltered(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Array<main.SearchResult>>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<main.Attachment>,arg4:string):Promise<void>;

export function SendTyping(arg1:boolean):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function SetAudioSettings(arg1:number,arg2:number,arg3:boolean,arg4:number,arg5:boolean):Promise<void>;

export function SetCameraOutputs(arg1:boolean,arg2:boolean):Promise<void>;

export function SetLevelMeter(arg1:boolean):Promise<void>;

export function SetMessagePinned(arg1:string,arg2:boolean):Promise<void>;

export function SetPresence(arg1:string):Promise<void>;

export function SetScreenPreview(arg1:boolean):Promise<void>;

export function SetScreenShareEnabled(arg1:boolean):Promise<void>;

export function SetScreenViewLimit(arg1:number,arg2:number):Promise<void>;

export function SetServerNickname(arg1:string):Promise<void>;

export function SetStreamVideoLag(arg1:string,arg2:number):Promise<void>;

export function SetTranscodeSettings(arg1:number,arg2:boolean,arg3:boolean):Promise<void>;

export function SetUserAudio(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetVideoCodec(arg1:string):Promise<void>;

export function SetVideoEnabled(arg1:boolean):Promise<void>;

export function SetVoiceSmoothing(arg1:boolean):Promise<void>;

export function StartCamera(arg1:main.CameraStart):Promise<string>;

export function StartMicTest(arg1:string,arg2:string):Promise<void>;

export function StartScreenShare(arg1:main.ScreenStart):Promise<string>;

export function StopCamera():Promise<void>;

export function StopMicTest():Promise<void>;

export function StopScreenShare():Promise<void>;

export function SubscribeBoard(arg1:string):Promise<void>;

export function ToggleDeafen():Promise<boolean>;

export function ToggleMute():Promise<boolean>;

export function UnlockAccount(arg1:string):Promise<main.AccountView>;

export function UpdateEmoji(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateServer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.SavedServer>>;

export function UpdateStatus():Promise<main.UpdateStatus>;

export function UpdateSticker(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UploadEmojiData(arg1:string,arg2:string):Promise<main.CustomEmoji>;

export function UploadEmojiFile(arg1:string,arg2:string):Promise<main.CustomEmoji>;

export function UploadFile(arg1:string):Promise<main.UploadResult>;

export function UploadFileData(arg1:string,arg2:string):Promise<main.UploadResult>;

export function UploadFileWithProgress(arg1:string,arg2:string):Promise<main.UploadResult>;

export function UploadStickerData(arg1:string,arg2:string,arg3:string):Promise<main.Sticker>;

export function UploadStickerFile(arg1:string,arg2:string,arg3:string):Promise<main.Sticker>;

export function VideoConversionInfo():Promise<Record<string, any>>;

export function VideoSendCodec():Promise<string>;

export function WatchScreen(arg1:string,arg2:boolean):Promise<void>;
