// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetBoards(arg1) {
  return window['go']['main']['App']['GetBoards'](arg1);
}

export function GetRooms() {
  return window['go']['main']['App']['GetRooms']();
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SubscribeBoard(arg1) {
  return window['go']['main']['App']['SubscribeBoard'](arg1);
}
